// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_EOW3DVOd1sDvsosVy1AswbI99t-LqqM',
    appId: '1:1003242235892:web:f9122e3520efd57e9c3ba1',
    messagingSenderId: '1003242235892',
    projectId: 'easy-finance-d7f01',
    authDomain: 'easy-finance-d7f01.firebaseapp.com',
    storageBucket: 'easy-finance-d7f01.appspot.com',
    measurementId: 'G-KEZSM0CZHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrRbzaomESbrL1nSgAccylOw5V6G3f-oQ',
    appId: '1:1003242235892:android:874274b61e116a4e9c3ba1',
    messagingSenderId: '1003242235892',
    projectId: 'easy-finance-d7f01',
    storageBucket: 'easy-finance-d7f01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2XbVFtv-Nc6OJuqSXVKiVM6Zah0SetwY',
    appId: '1:1003242235892:ios:8a334f77a51135239c3ba1',
    messagingSenderId: '1003242235892',
    projectId: 'easy-finance-d7f01',
    storageBucket: 'easy-finance-d7f01.appspot.com',
    iosClientId: '1003242235892-1npm57ph2c49l3tvf8drt349c7leej44.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBiolerlate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2XbVFtv-Nc6OJuqSXVKiVM6Zah0SetwY',
    appId: '1:1003242235892:ios:8a334f77a51135239c3ba1',
    messagingSenderId: '1003242235892',
    projectId: 'easy-finance-d7f01',
    storageBucket: 'easy-finance-d7f01.appspot.com',
    iosClientId: '1003242235892-1npm57ph2c49l3tvf8drt349c7leej44.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBiolerlate',
  );
}
